### ISSUE TITLE
[Feat]: 책 데이터 관련 api 기능 구현

### ISSUE THREAD

**Issue by CH4MD0M** [prgrms-fe-devcourse/NFE1-1-3-KR#2]
## 📌 작업 내용

책 데이터 관련 API 함수 구현

<br/>

## ✅ To-Do

- [ ] supabase 설치 및 설정
- [ ] 전체 책 목록을 조회하는 API 함수 구현
- [ ] 책 ID를 통해 책 상세 정보를 조회하는 API 함수 구현

<br/>

## 📝 참고사항

리액트쿼리 사용할 때, 범위를 지정해서 수가적으로 불러오도록 수정해야 함
[참고링크](https://supabase.com/docs/reference/javascript/range)
