### ISSUE TITLE
[Feat]: 게시글 좋아요 api 구현

### ISSUE THREAD

**Issue by CH4MD0M** [prgrms-fe-devcourse/NFE1-1-3-KR#30]
## 📌 작업 내용

커뮤니티(게시글) 좋아요 api 구현

<br/>

## ✅ To-Do

- [ ] 게시글 좋아요 카운트 컬럼 추가
- [ ] 게시글 좋아요 api 구현
- [ ] 게시글 좋아요 취소 api 구현
