### ISSUE TITLE
[Feat]: 상세 모달 화면 레이아웃 작업

### ISSUE THREAD

**Issue by hoon-hoon** [prgrms-fe-devcourse/NFE1-1-3-KR#4]
## 📌 작업 내용
선택된 책의 상세 정보를 보여줄 모달 화면을 구현
- 파라미터로 전달된 책 id를 통해 API를 호출해 상세정보를 받아옵니다.
- 모달은 클릭한 책의 커버, 제목, 저자, 카테고리, 별점, 설명, 북마크를 노출합니다.
- 오른쪽 상단에 모달을 닫을 수 있는 버튼을 배치합니다.
- 북마크는 상단에서 내려오는 인터랙티브한 애니메이션을 적용할 예정입니다.

<br/>

## ✅ To-Do

- [x] 책 정보 레이아웃 구현
- [x] 모달 닫기 버튼
- [x] 책갈피 애니메이션 구현
- [x] 파라미터 기반 API 호출로 책 상세 정보 가져오기

<br/>

## 📝 참고사항

- 빠르게 완료 후 PR 하겠습니다.
- 추후 상태 관리 로직이나 다른 컴포넌트와의 연결 작업이 필요합니다.

![pr_4](https://github.com/user-attachments/assets/79450d3d-d815-409a-87fd-a5d7de2f672b)

---
