### ISSUE TITLE
[Refact]: 헤더 로그인 버튼 토글 기능 추가

### ISSUE THREAD

**Issue by CH4MD0M** [prgrms-fe-devcourse/NFE1-1-3-KR#44]
## 📌 작업 내용

헤더 아이콘에 로그인 버튼이 들어가도록 수정합니다.
로그인 모달 ui를 수정합니다.

<br/>

## ✅ To-Do

- [ ] 로그인 모달 ui 변경
- [ ] protected routes 설정(마이 페이지)
- [ ] 헤더 메뉴 로그인, 마이페이지 아이콘 토글되록 수정
