### ISSUE TITLE
[Feat]: 슬라이더 검색 기능 구현

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-fe-devcourse/NFE1-1-3-KR#48]
## 📌 작업 내용

- 슬라이더의 API 기능을 분리하고, 검색 기능을 구현할 생각입니다.
<br/>

## ✅ To-Do

- [x] 인기 슬라이더 컴포넌트와 API 분리
- [x] 검색 기능 구현
- [x] 검색 기능 디바운스 적용
- [x] 메뉴 검색 버튼과 연결

<br/>
