### ISSUE TITLE
[Feat]: 메인 검색 페이지 UI 구현

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-fe-devcourse/NFE1-1-3-KR#55]
## 📌 작업 내용

- 현재는 슬라이더만 구현한 상태라 전반적인 페이지 UI를 구현하려 합니다.
<br/>

## ✅ To-Do

- [x] 타이틀 및 구름 추가
- [x] No results found 추가
- [x] 슬라이더 애니메이션 및 효과 수정

<br/>
