### ISSUE TITLE
[Feat]: Slider 컴포넌트 스타일링

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-fe-devcourse/NFE1-1-3-KR#6]
## 📌 작업 내용

- 인기 도서 리스트 화면을 구성하는 Slider 컴포넌트를 스타일링합니다.
- Slider 컴포넌트는 carousel slider 형태이며, 아래와 같이 컴포넌트를 구현합니다.
    - Slider 컴포넌트
        - SliderItem 컴포넌트

<br/>

## ✅ To-Do

- [x] SliderItem 컴포넌트 구현
- [x] Slider 컴포넌트 스타일링
     - [x] 원형 배치 레이아웃 구현
     - [x] 반응형 구현

<br/>

## 📝 참고사항

- 원형 배치 슬라이드는 처음이라 익숙지 않지만, 최대한 빠르게 완료 후 PR 하겠습니다.
- Gsap을 사용한 기능 구현은 다른 브랜치에서 진행하겠습니다.
