### ISSUE TITLE
[Fix]: 메인 페이지 모바일 레이아웃 수정

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-fe-devcourse/NFE1-1-3-KR#67]
## 📌 작업 내용

- 메인 페이지 타이틀이 글씨가 크고, 드래그 되는 부분이 있어 수정하려 합니다.
- 부차적으로 슬라이더, 그리드, 검색바 등 모바일에서의 레이아웃을 수정합니다.
<br/>

## ✅ To-Do

- [x] 글자 크기 수정
- [x] 타이틀 드래그 방지
- [x] 슬라이더 레이아웃 수정
- [x] 그리드 레이아웃 수정
- [x] 검색바 너비 수정

<br/>
