### ISSUE TITLE
[Feat]: Slider 컴포넌트 관련 이벤트 구현 (드래그, inactive한 Item 클릭)

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-fe-devcourse/NFE1-1-3-KR#9]
## 📌 작업 내용

- Slider 컴포넌트의 회전 애니메이션 및 드래그,  inactive한 Item 클릭 이벤트를 구현합니다.
- 드래그 시 슬라이더가 회전합니다.
- active가 아닌 Item을 클릭 시 item이 active한 위치(정중앙)로 이동합니다.

<br/>

## ✅ To-Do

- [x] 슬라이더 회전 애니메이션 구현
- [x] 슬라이더 드래그 이벤트 구현
- [x] 슬라이더 active가 아닌 Item의 클릭 이벤트 구현
- [x] active 클릭 이벤트 구현
- [x] 슬라이더 스크롤 이벤트 구현

<br/>

## 📝 참고사항

- 스크롤 이벤트와 active된 Item의 클릭 이벤트는 작업 시간이 오래 걸릴 것 같아 따로 둘은 따로 분리하겠습니다.
